### ISSUE TITLE
Version of DynamoDB out of date

### ISSUE THREAD

**Issue by christopherobin** [AerisCloud/ansible-dynamodb#3]
Seeing the last PR I realized that the version we ship with this role is getting old, maybe we should take this occasion to bump it to `2016-05-17` or just use `latest` and let the user lock the version themselves?

Maybe add a link to https://s3-us-west-2.amazonaws.com/dynamodb-local/ so that users can find which version they want.

**Comment by MiLk** [comment]
PR are always welcome :)

**Comment by christopherobin** [comment]
I was probing for an opinion too before doing the actual PR :smile:

**Comment by MiLk** [comment]
Maybe we can reuse some of the work done by @byronwong and @miyanaga
* https://github.com/AerisCloud/ansible-dynamodb/compare/master...classdojo:master
* https://github.com/AerisCloud/ansible-dynamodb/compare/master...miyanaga:master

With the work already done in #2, it should help improving the quality of this role.

**Comment by christopherobin** [comment]
I'll try to look at merging #2 and make a new PR to get some of those changes in next week, also should we lock the version or just use `latest` in default?

**Comment by MiLk** [comment]
Version should be locked.
We can add instructions in the README to use `latest`.

**Comment by christopherobin** [comment]
:+1:
