### ISSUE TITLE
is trailing period a typo 

### ISSUE THREAD

**Issue by kknd22** [AerisCloud/ansible-dynamodb#5]
https://github.com/AerisCloud/ansible-dynamodb/blob/master/defaults/main.yml  
`dynamodb_sha: 832d474316c9d092de8c24885e69c9be9e22b9807e7383e0de6f247e44601a90.`  
Noticed the trailing period after `...1a90` - is this a typo?
Thanks

-cl

**Comment by MiLk** [comment]
Yes, probably.

@christopherobin Please confirm.

**Comment by christopherobin** [comment]
That is indeed a typo, I could fix that today, adding both tests and updating to 2017-01-24 which seems to be the latest version
